version: '2'

networks:
  sb:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
     - sb

  kafka:
    build: .
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CREATE_TOPICS: "log:1:1,verify:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - sb

  consumer:
    build: 
      context: ../../kafka-1/kafka-1-consumer
    ports:
      - "8090:8090"
    environment:
      spring.kafka.bootstrap-servers: localhost:9092
    links:
     - kafka
    networks:
     - sb
      
  producer:
    build: 
      context: ../../kafka-1/kafka-1-producer
    ports:
      - "8190:8190"
    environment:
      spring.kafka.bootstrap-servers: localhost:9092
    links:
     - kafka
    networks:
     - sb
