apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: internal
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: external
      port: 29092
      protocol: TCP
      targetPort: 29092
      nodePort: 32000
  selector:
    app: kafka
  type: NodePort