kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: HOSTNAME_COMMAND
              value: echo 192.168.99.100
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: _{HOSTNAME_COMMAND}:32200
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://:9092,EXTERNAL://_{HOSTNAME_COMMAND}:32000
            - name: KAFKA_LISTENERS
              value: INTERNAL://:9092,EXTERNAL://:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_BROKER_ID
              value: '1'
            - name: KAFKA_CREATE_TOPICS
              value: 'log:1:1'
